// Extra icon definitions; convenient when we want to pick an icon based on some passed-in values
// ===============================================================================

var icons = {}

icons['wave1'] = 'hud/img/icons/Crab.png'
icons['wave2'] = 'hud/img/icons/Wale.png'
icons['wave3'] = 'hud/img/icons/Hopper.png'
icons['wave4'] = 'hud/img/icons/FlyingChicken.png'
icons['wave5'] = 'hud/img/icons/Scorpion.png'
icons['wave6'] = 'hud/img/icons/Rocko.png'
icons['wave7'] = 'hud/img/icons/Sludge.png'
icons['wave8'] = 'hud/img/icons/Kobra.png'
icons['wave9'] = 'hud/img/icons/Carapace.png'
icons['wave10'] = 'hud/img/icons/Granddaddy.png'
icons['wave11'] = 'hud/img/icons/QuillShooter.png'
icons['wave12'] = 'hud/img/icons/Mantis.png'
icons['wave13'] = 'hud/img/icons/DrillGolem.png'
icons['wave14'] = 'hud/img/icons/KillerSlug.png'
icons['wave15'] = 'hud/img/icons/Quadrapus.png'
icons['wave16'] = 'hud/img/icons/Cardinal.png'
icons['wave17'] = 'hud/img/icons/MetalDragon.png'
icons['wave18'] = 'hud/img/icons/WaleChief.png'
icons['wave19'] = 'hud/img/icons/DireToad.png'
icons['wave20'] = 'hud/img/icons/Maccabeus.png'
icons['wave21'] = 'hud/img/icons/LegionLord.png'

icons['overallElo'] = 'hud/img/icons/AlphaTop100.png'
icons['overallEloThisSeasonAtLeastOneGamePlayed'] = 'hud/img/icons/AlphaTop100.png'
icons['overallPeakEloThisSeason'] = 'hud/img/icons/AlphaTop10.png'
icons['overallPeakEloThisSeasonAtLeastOneGamePlayed'] = 'hud/img/icons/AlphaTop10.png'
icons['overallPeakElo'] = 'hud/img/icons/Ranks/Grandmaster.png'
icons['rankedWinsThisSeason'] = 'hud/img/icons/ShurikenCyclone.png'
icons['classicWinsThisSeason'] = 'hud/img/icons/ArmWithShuriken.png'
icons['vipOverallElo'] = 'hud/img/icons/Secret/NoTouchyYozora.png'
icons['vipOverallPeakElo'] = 'hud/img/icons/Secret/NoTouchyYozora.png'
icons['vipTotalMatchmadeWins'] = 'hud/img/icons/Secret/CrownOfBling.png'
icons['eventPoints'] = 'hud/img/icons/EventPoints.png'
icons['atlanteanElo'] = 'hud/img/icons/Atlantean.png'
icons['elementElo'] = 'hud/img/icons/Element.png'
icons['forsakenElo'] = 'hud/img/icons/Forsaken.png'
icons['groveElo'] = 'hud/img/icons/Grove.png'
icons['mechElo'] = 'hud/img/icons/Mech.png'
icons['nomadElo'] = 'hud/img/icons/Nomad.png'
icons['shrineElo'] = 'hud/img/icons/Shrine.png'
icons['divineElo'] = 'hud/img/icons/Divine.png'
icons['ladderPoints'] = 'hud/img/icons/LadderPoints.png'

icons['totalXp'] = 'hud/img/icons/LegionLord.png'
icons['atlanteanXp'] = 'hud/img/icons/Atlantean.png'
icons['elementXp'] = 'hud/img/icons/Element.png'
icons['forsakenXp'] = 'hud/img/icons/Forsaken.png'
icons['groveXp'] = 'hud/img/icons/Grove.png'
icons['mechXp'] = 'hud/img/icons/Mech.png'
icons['nomadXp'] = 'hud/img/icons/Nomad.png'
icons['mastermindXp'] = 'hud/img/icons/Mastermind.png'
icons['shrineXp'] = 'hud/img/icons/Shrine.png'
icons['divineXp'] = 'hud/img/icons/Divine.png'

icons['collectionValue'] = 'hud/img/icons/Coin.png'
icons['countryCollectionValue'] = 'hud/img/icons/Venture.png'
icons['behaviorScore'] = 'hud/img/icons/Afk.png'
icons['weeklyChallengeFirstPlaceWins'] = 'hud/img/icons/ChallengerElite.png'
icons['weeklyChallengeWins'] = 'hud/img/icons/Challenger.png'
icons['guildWarVictoryPoints'] = 'hud/img/icons/GuildWarVP.png'
icons['guildWarWins'] = 'hud/img/icons/GuildWar.png'
icons['guildXp'] = 'hud/img/icons/GuildLevel.png'

icons['border_rating-bronze'] = 'hud/img/loading/Bronze.png'
icons['border_rating-silver'] = 'hud/img/loading/Silver.png'
icons['border_rating-gold'] = 'hud/img/loading/Gold.png'
icons['border_rating-platinum'] = 'hud/img/loading/Platinum.png'
icons['border_rating-diamond'] = 'hud/img/loading/Diamond.png'
icons['border_rating-expert'] = 'hud/img/loading/Expert.png'
icons['border_rating-master'] = 'hud/img/loading/Master.png'
icons['border_rating-seniormaster'] = 'hud/img/loading/SeniorMaster.png'
icons['border_rating-grandmaster'] = 'hud/img/loading/GrandMaster.png'
icons['border_rating-legend'] = 'hud/img/loading/Legend.png'

icons['x2'] = 'hud/img/icons/mode_x2.png'
icons['chaos'] = 'hud/img/icons/mode_chaos.png'
icons['hybrid'] = 'hud/img/icons/mode_hybrid.png'
icons['prophet'] = 'hud/img/icons/mode_prophet.png'
icons['not1s'] = 'hud/img/icons/mode_no_t1s.png'
icons['allvisible'] = 'hud/img/icons/mode_all_visible.png'
icons['extragold'] = 'hud/img/icons/allowance.png'
icons['nosaving'] = 'hud/img/icons/mode_ns.png'
icons['teammercs'] = 'hud/img/icons/Mercenaries.png'
icons['duel'] = 'hud/img/icons/mode_duel.png'
icons['mastermind'] = 'hud/img/icons/Mastermind.png'
